//OT QUERY 14
export enum OTGrillaEnum {
  folio = 1,
  validado = 2,
  ubicacion = 3,
  estado_id = 4,
  estado = 5,
  estado_impresion = 6,
  punto_venta = 7,
  proyecto_titulo = 8,
  proyecto = 9,

  numero_reporte_atencion = 10,
  establecimiento = 11,
  comuna = 12,
  numero_envio = 13,
  numero_reporte_firma = 14,
  numero_guia = 15,

  cliente_rut = 16,
  cliente_nomnbre = 17,
  fecha_atencion = 18,
  tipo_anteojo_id = 19,
  tipo_anteojo = 20,
  a1_armazon_id = 21,
  a2_armazon_id = 22,
  a3_armazon_id = 23,
  cr1_od = 24,
  cr1_oi = 25,
  cr2_od = 26,
  cr2_oi = 27,

  estado_validacion = 28,
  por_vencer = 29,
  numero_oc = 30,
  numero_factura = 31,
  imprime_qr = 32,
  imprime_ticket = 33,
  require_guia = 34,

  usuario = 35,
  estado_wsp = 36,
  opcion_montaje = 37,
  validar_parametrizacionm = 38,
  motivo = 39,
}
