//OT QUERY 14
export enum OTGrillaEnum {
  folio = 1,
  ubicacion = 2,
  motivo = 3,
  estado_id = 4,
  estado = 5,
  estado_impresion = 6,
  punto_venta = 7,
  proyecto_titulo = 8,
  proyecto = 9,
  establecimiento = 10,
  cliente_rut = 11,
  cliente_nomnbre = 12,
  fecha_atencion = 13,
  tipo_anteojo_id = 14,
  tipo_anteojo = 15,
  a1_armazon_id = 16,
  a2_armazon_id = 17,
  a3_armazon_id = 18,
  cr1_od = 19,
  cr1_oi = 20,
  cr2_od = 21,
  cr2_oi = 22,
  estado_validacion = 23,
  numero_envio = 24,
  numero_reporte_firma = 25,
  numero_reporte_atencion = 26,

  por_vencer = 27,
  numero_oc = 28,

  numero_guia = 29,
  numero_factura = 30,

  imprime_qr = 31,
  imprime_ticket = 32,

  usuario = 33,
  estado_wsp = 34,
  opcion_montaje = 35,
  require_guia = 36,
  validar_parametrizacionm = 37,
}
