export enum ReservaArmazonesEnum {
  cliente_rut = 1,
  proyecto = 2,
  proyecto_titulo = 3,
  punto_venta_id = 4,
  punto_venta = 5,
  tipo_anteojo_id = 6,
  tipo_anteojo = 7,
  dp = 8,
  cod_armazon1 = 9,
  cod_armazon2 = 10,
  cod_armazon3 = 11,
  usuario_id = 12,
  usuario = 13,
  fecha_hora = 14,
  diametro = 15,
}
