export enum ReservaArmazonesEnum {
  cliente_rut = 1,
  proyecto = 2,
  proyecto_titulo = 3,
  punto_venta_id = 4,
  punto_venta = 5,
  tipo_anteojo_id = 6,
  tipo_anteojo = 7,
  dp1 = 8,
  dp2 = 9,
  diametro = 10,
  cod_armazon1 = 11,
  cod_armazon2 = 12,
  cod_armazon3 = 13,
  usuario_id = 14,
  usuario = 15,
  fecha_hora = 16,
}
